name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # @v4 ist die aktuelle Version

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"

          directory: "custom_components/growspace_manager"
          filename: "growspace_manager.zip"
          exclusions: "*.git* .editorconfig *.vscode* *.github* .coverage pytest.ini module.json"

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "growspace_manager.zip"
          asset_name: "growspace_manager.zip"
          tag: ${{ github.ref }}
          overwrite: true
