name: Build Release ZIP

on:
  release:
    types: [published]

jobs:
  build_release:
    name: Build Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZIP Release
        run: |
          cd custom_components
          zip -r ../growspace_manager.zip ./growspace_manager

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./growspace_manager.zip
          asset_name: growspace_manager.zip
          asset_content_type: application/zip
