name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Creates the ZIP file
      - name: ZIP Release
        run: |
          cd custom_components/growspace_manager
          zip -r ../../growspace_manager.zip . \
            -x ".github/*" \
            -x ".coverage" \
            -x ".gitignore" \
            -x "pytest.ini" \
            -x "module.json"

      # 3. Creates the GitHub Release and attaches the new zip file
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: growspace_manager.zip
